name: Build

on:
  push:
    branches:
      - master
      - gh_actions

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Autogen
        run: ./autogen.sh

      - name: ENOENT
        run: sed -i '41s/ENOENT/ENOENT || errno == EINVAL/' gnulib/tests/test-readlink.h

      - name: Configure
        run: ./configure

      - name: Make
        run: make

      - name: Make check
        run: make check VERBOSE=1

      - name: Valgrind
        run: ./src/try valgrind
